### ISSUE TITLE
您好，一直无法触发onPictureGenerated该怎么排查，可以提供一下思路吗

### ISSUE THREAD

**Issue by sumcets** [liyufengrex/flutter_printer_plus#3]
flutter版本3.0.4

**Comment by liyufengrex** [comment]
你好，PrintImageGenerateWidget 需要放在整个树结构的顶层，也就是 MaterialApp 节点的下一级，保证不会因为页面push造成PrintImageGenerateWidget节点不可见，因为不可见的节点不会渲染，会出现 onPicGenerated 不响应。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年01月07日 09:23 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [liyufengrex/flutter_printer_plus] 您好，一直无法触发onPictureGenerated该怎么排查，可以提供一下思路吗 (Issue #3) |

Closed #3 as completed.
